---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages('dplyr')
library('dplyr')
```

```{r Import}

arrecadacao_estado <- read.table(
  file = "C:/Users/20221bsi0455/estudo-bi-arrec-estados/dataset/arrecadacao-estado.csv", fileEncoding="latin1", sep=";", dec=',', check.names=F)

arrecadacao_estado
```

# Tratar colunas com valores nulos.

OBS: Como esse dataset é sobre arrecadação de impostos a falta de um valor significa que não existia esse imposto no período de registro. Portanto a substituição dos valores **NULOS** por **ZERO** faz sentido.

```{r}
cols_with_missing <- colnames(arrecadacao_estado)[apply
    (arrecadacao_estado, 2, anyNA)
]

arrecadacao_estado[cols_with_missing] <- lapply(
  arrecadacao_estado[cols_with_missing],
  function(x) replace(x, is.na(x), 0)
)
```

# Qual o estado que mais arrecadou em 2023?

```{r}
df_filtered <- arrecadacao_estado[arrecadacao_estado["Ano"] == 2023]

grouped_by_uf_ano <- df_filtered.groupby("UF", "Ano") %>% 
  summarise_across(sum, .cols = everything()[-which(names(df_filtered) == "Mês")])

```

```{r}
df_filtered %>% 
  group_by(x(Ano, Uf)) %>%
  summarise(across())
```
